version: '3.9'
services:
    integrationtest:
        build:
            context: ./
            dockerfile: Docker_testintegration/Dockerfile
        volumes: 
            - .:/altility
    
    unittest:
        build:
            context: ./
            dockerfile: Docker_testunit/Dockerfile
        volumes:
            - .:/altility
